[package]
name = "heap-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotter = { path = "../plotter" }
two_three = "0.0.6"
rand =  "0.8.4"
